services:
  db:
    build:
      context: postgres-db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-multinetwork:/var/lib/postgresql/data
    ports:
      - "5234:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=dracula
volumes:
  postgres-multinetwork:
