services:
  db:
    restart: unless-stopped
    build:
      context: postgres-db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-multinetwork:/var/lib/postgresql/data
  users-api:
    restart: on-failure
    depends_on:
      - db
    build:
      context: users-api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=123456
      - PORT=3050
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - AUTH_API_HOST=auth-api
      - AUTH_API_PORT=3051
  tasks-api:
    restart: on-failure
    depends_on:
      - db
    build:
      context: tasks-api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_DB=tasks
      - POSTGRES_PASSWORD=123456
      - PORT=3052
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - AUTH_API_HOST=auth-api
      - AUTH_API_PORT=3051
  auth-api:
    restart: on-failure
    build:
      context: auth-api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_DB=auth
      - POSTGRES_PASSWORD=123456
      - PORT=3051
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PASSWORD_PEPPER=XeDRMzq9HpuWL2ZYBw2BDi1sxjT5dnOSdOFEU00wvpo=
      - JWT_SECRET=Q5nT18OkUuHam/Y5BRbzY3SYlwNqpJRdvYVwS/gzecc=
  frontend:
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - USERS_API_HOST=users-api
      - USERS_API_PORT=3050
      - TASKS_API_HOST=tasks-api
      - TASKS_API_PORT=3052
    depends_on:
      - users-api
      - tasks-api
      - auth-api
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=dracula
volumes:
  postgres-multinetwork:
