apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #efs-claim
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi