apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api
spec:
  replicas: 3
  selector:
    matchLabels:
      api: tasks-api
  template:
    metadata:
      labels:
        api: tasks-api
        api-type: external
    spec:
      initContainers:
        - name: init-postgres
          imagePullPolicy: IfNotPresent
          image: busybox:1.36.0
          command:
            [
              "sh",
              "-c",
              "until nc -vz db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 5432; do echo waiting for db; sleep 2; done",
            ]
      containers:
        - name: tasks-api
          image: jym272/multinetwork-tasks-api:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: jorge
            - name: POSTGRES_DB
              value: tasks
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: PORT
              value: $(TASKS_API_SERVICE_PORT_TASKS_API)
            - name: POSTGRES_HOST
              value: $(DB_SERVICE_HOST)
            - name: POSTGRES_PORT
              value: $(DB_SERVICE_PORT_POSTGRES)
            - name: AUTH_API_HOST
              value: $(AUTH_API_SERVICE_HOST)
            - name: AUTH_API_PORT
              value: $(AUTH_API_SERVICE_PORT_AUTH_API)
