services:
  kubectl:
    working_dir: /root
    image: alpine/k8s:1.23.16
    volumes:
      - kube:/root/.kube
      - ../k8s:/root/k8s
      - /root/k8s/pvc
      - ~/.aws:/root/.aws
      - ./files:/root/files
volumes:
  kube:

