#!/usr/bin/env bash

set -euo pipefail

# create
# https://eksctl.io/usage/creating-and-managing-clusters/
eksctl create cluster -f cluster.yaml

#delete
eksctl delete cluster -f cluster.yaml

#apply kubectl
kubectl apply -f k8s/service.yaml && kubectl apply -f k8s
# delete
kubectl delete -f k8s