services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-db3:/var/lib/postgresql/data
    command: |
      sh -c "echo 'CREATE DATABASE auth;CREATE DATABASE tasks;' > /docker-entrypoint-initdb.d/init.sql;
      exec docker-entrypoint.sh postgres"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  postgres-db3:
